[package]
name = "inline-test"
version = "0.1.2"
edition = "2021"
description = "Extract and process inline test comments from Rust source files."
repository = "https://github.com/gvozdvmozgu/inline-test/"
license = "MIT OR Apache-2.0"

[dependencies]
